// flow-typed signature: ed5c4c1d3f900232331fd0e1c7ebc6aa
// flow-typed version: <<STUB>>/bricks.js_v^1.8.0/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bricks.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bricks.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bricks.js/dist/bricks' {
  declare module.exports: any;
}

declare module 'bricks.js/dist/bricks.module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bricks.js/dist/bricks.js' {
  declare module.exports: $Exports<'bricks.js/dist/bricks'>;
}
declare module 'bricks.js/dist/bricks.module.js' {
  declare module.exports: $Exports<'bricks.js/dist/bricks.module'>;
}
