// flow-typed signature: 5c1fc86fdc14cb9ae94cf05c951464f6
// flow-typed version: <<STUB>>/inferno_v^7.4.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'inferno/dist/index.cjs.min' {
  declare module.exports: any;
}

declare module 'inferno/dist/index.dev.esm' {
  declare module.exports: any;
}

declare module 'inferno/dist/index.esm' {
  declare module.exports: any;
}

declare module 'inferno/dist/index.esnext' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno' {
  declare module.exports: any;
}

declare module 'inferno/dist/inferno.min' {
  declare module.exports: any;
}

declare module 'inferno/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno/dist/index.cjs.js' {
  declare module.exports: $Exports<'inferno/dist/index.cjs'>;
}
declare module 'inferno/dist/index.cjs.min.js' {
  declare module.exports: $Exports<'inferno/dist/index.cjs.min'>;
}
declare module 'inferno/dist/index.dev.esm.js' {
  declare module.exports: $Exports<'inferno/dist/index.dev.esm'>;
}
declare module 'inferno/dist/index.esm.js' {
  declare module.exports: $Exports<'inferno/dist/index.esm'>;
}
declare module 'inferno/dist/index.esnext.js' {
  declare module.exports: $Exports<'inferno/dist/index.esnext'>;
}
declare module 'inferno/dist/inferno.js' {
  declare module.exports: $Exports<'inferno/dist/inferno'>;
}
declare module 'inferno/dist/inferno.min.js' {
  declare module.exports: $Exports<'inferno/dist/inferno.min'>;
}
declare module 'inferno/index.esm.js' {
  declare module.exports: $Exports<'inferno/index.esm'>;
}
declare module 'inferno/index' {
  declare module.exports: $Exports<'inferno'>;
}
declare module 'inferno/index.js' {
  declare module.exports: $Exports<'inferno'>;
}
