// flow-typed signature: bf93045dcefd2321b88f8fa2572a70de
// flow-typed version: <<STUB>>/match-media-mock_v^0.1.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'match-media-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'match-media-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'match-media-mock/lib/MatchMediaMock' {
  declare module.exports: any;
}

declare module 'match-media-mock/lib/MediaQueryListMock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'match-media-mock/lib/MatchMediaMock.js' {
  declare module.exports: $Exports<'match-media-mock/lib/MatchMediaMock'>;
}
declare module 'match-media-mock/lib/MediaQueryListMock.js' {
  declare module.exports: $Exports<'match-media-mock/lib/MediaQueryListMock'>;
}
